// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";

function toPosixPath(input: string) {
  return input.split(path.sep).join("/");
}

function defaultDatabaseUrl() {
  return `file:${toPosixPath(path.resolve(process.cwd(), "data", "oax.db"))}`;
}

function normalizeDatabaseUrl(rawValue: string | undefined) {
  if (!rawValue) return defaultDatabaseUrl();
  if (!rawValue.startsWith("file:")) return rawValue;

  const body = rawValue.slice("file:".length);
  const queryIndex = body.indexOf("?");
  const dbPath = queryIndex === -1 ? body : body.slice(0, queryIndex);
  const suffix = queryIndex === -1 ? "" : body.slice(queryIndex);

  if (!dbPath || dbPath === ":memory:") return rawValue;
  if (path.isAbsolute(dbPath)) return `file:${toPosixPath(dbPath)}${suffix}`;

  return `file:${toPosixPath(path.resolve(process.cwd(), dbPath))}${suffix}`;
}

const databaseUrl = normalizeDatabaseUrl(process.env["DATABASE_URL"]);
process.env["DATABASE_URL"] = databaseUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
